[dev]
  command = "vite"
  targetPort = 5173
  port = 8000

[build]
  command = "pnpm build"
  functions = "src/functions"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200